version: '3.8'

services:
  stirling-pdf:
    container_name: stirling-pdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/tessdata:/usr/share/tessdata:rw
      - ./data/configs:/configs:rw
      - ./data/customFiles:/customFiles:rw
      - ./data/logs:/logs:rw
      - ./data/pipeline:/pipeline:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      SECURITY_CSRFDISABLED: "true"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      DISABLE_ADDITIONAL_FEATURES: "false"
      LANGS: "en_US,en_GB,de_DE,fr_FR,es_ES,zh_CN,zh_TW,ca_CA,it_IT,sv_SE,pl_PL,ro_RO,ko_KR,pt_BR,ru_RU,el_GR,hi_IN,hu_HU,tr_TR,id_ID"
      SYSTEM_DEFAULTLOCALE: "en_US"
      UI_APPNAME: "Stirling PDF"
      UI_HOMEDESCRIPTION: "Your locally hosted PDF manipulation toolkit"
      UI_APPNAMENAVBAR: "Stirling PDF"
      SYSTEM_MAXFILESIZE: "2000"
      SYSTEM_CONNECTIONTIMEOUTMINUTES: "5"
      SYSTEM_ENABLEANALYTICS: "false"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M